---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: create eks cluster and node groups
      command: eksctl create cluster --name {{ cluster_name }} --region {{ region }} --nodegroup-name {{ nodegroup_name }} --node-type {{ node_type }} --nodes {{ nodes }} --nodes-min {{ nodes_min }} --nodes-max {{ nodes_max }} --managed
