
---

- name: Create eks cluster
  hosts: localhost
  tasks:
    - name: create an EKS cluster
      community.aws.eks_cluster:
        name: Ansible-EKS-CLUSTER
        version: 1.27
        role_arn: arn:aws:iam::625243961866:role/EksClusterRole
        subnets:
          - subnet-0c819740100e5e234
          - subnet-08cfb65242d6db186
        security_groups:
          - EKS-SECURITY-GROUP
          - sg-089d63d142e1a9e73
      register: caller_facts
