---

- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Check if EKS Cluster exists
      shell: eksctl get cluster --name {{ cluster_name }}
      register: eks_cluster_output
      ignore_errors: yes  # Ignore the error if the cluster doesn't exist yet

    - name: Create EKS Cluster and Node Groups
      shell: eksctl create cluster --name {{ cluster_name }} --region {{ region }} --nodegroup-name {{ nodegroup_name }} --node-type {{ node_type }} --nodes {{ nodes }} --nodes-min {{ nodes_min }} --nodes-max {{ nodes_max }} --managed
      when: eks_cluster_output.rc != 0  # Execute this task only if the cluster doesn't exist
    
    - name: Wait for EKS Cluster to be ready
      wait_for:
        timeout: 600  # Adjust the timeout as needed (in seconds)
        host: "{{ cluster_name }}"
        port: 443
        state: started
      when: eks_cluster_output.rc != 0  # Wait only if the cluster is being created

    - name: Deploy NGINX to EKS Cluster
      command: kubectl apply -f nginx.yaml
      args:
        chdir: nginx.yml  # Specify the full path to your deployment file
    # when: eks_cluster_output.rc == 0  e Execute this task if the cluster already exists or has just been created

