---
- hosts: localhost
  gather_facts: false
  vars_files:
    - eks-vars.yml

  tasks:
    - name: Check if EKS Cluster exists
      shell: eksctl get cluster --name {{ cluster_name }}
      register: eks_cluster_output
      ignore_errors: yes  # Ignore the error if the cluster does not exist yet.

    - name: Stop playbook if EKS Cluster exists
      meta: end_play
      when: eks_cluster_output.rc == 0  # If the return of the previous command is 0 (no error), stop the playbook.

    - name: Create EKS Cluster and Node Groups
      shell: eksctl create cluster --name {{ cluster_name }} --region {{ region }} --nodegroup-name {{ nodegroup_name }} --node-type {{ node_type }} --nodes {{ nodes }} --nodes-min {{ nodes_min }} --nodes-max {{ nodes_max }} --managed
